version: "3.8"

services:
  app1:
    build: .
    ports:
      - "52415:52415"
    networks:
      - exo_network

  app2:
    build: .
    ports:
      - "52416:52415"
    networks:
      - exo_network

networks:
  exo_network:
    driver: bridge
